### ISSUE TITLE
Amends to output.tf 

### ISSUE THREAD

**Issue by earthlingdavey** [cedi/cedi.dev#20]
Hi Cedi, 

Thanks for your post at https://cedi.dev/post/prod-ready-kubeone/

I think for completeness of *Reliability Tip 2: Don’t use the count meta-argument of terraform*

You could add the following output.tf amends.

```
# output.tf
output "ssh_commands" {
  value = [
    "ssh ${var.ssh_username}@hcloud_server.control_plane_1.ipv4_address",
    "ssh ${var.ssh_username}@hcloud_server.control_plane_2.ipv4_address",
    "ssh ${var.ssh_username}@hcloud_server.control_plane_3.ipv4_address"
  ]
}

output "kubeone_hosts" {
  description = "Control plane endpoints to SSH to"

  value = {
    control_plane = {
      hostnames = [
        hcloud_server.control_plane_1.name,
        hcloud_server.control_plane_2.name,
        hcloud_server.control_plane_3.name
      ]
      private_address = [
        hcloud_server_network.control_plane_1.ip,
        hcloud_server_network.control_plane_2.ip,
        hcloud_server_network.control_plane_3.ip
      ]
      public_address = [
        hcloud_server.control_plane_1.ipv4_address,
        hcloud_server.control_plane_2.ipv4_address,
        hcloud_server.control_plane_3.ipv4_address
      ]
      # ...
    }
  }
}
```

**Comment by cedi** [comment]
Hey @EarthlingDavey,
sorry, I totally missed this issue. You're absolutely right about this. 
I updated the post

**Comment by earthlingdavey** [comment]
No problem. And thanks again, your post was a real help.

**Comment by Unim8trix** [comment]
Hi and many(!) Thanks for this infos. I applied this changes to my terraform code (from KubeOne Hetzner example), but after the `terraform validate` fails with:

```bash
Error: Argument or block definition required
 
   on output.tf line 25:
   25: output “ssh_commands” {
 
 An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the argument value.
```

Line 25 in `output.tf`

```bash
output “ssh_commands” {
  value = [
    “ssh ${var.ssh_username}@hcloud_server.control_plane_1.ip_address”,
    “ssh ${var.ssh_username}@hcloud_server.control_plane_2.ip_address”,
    “ssh ${var.ssh_username}@hcloud_server.control_plane_3.ip_address”
  ]
}
```

I'm running Terraform v1.3.7 on darwin_arm64. Could you see what ham doing wrong?

**Comment by earthlingdavey** [comment]
@Unim8trix I'm not sure, but a known terraform version that works here is 1.3.1... 

Incase 1.3.7 isn't essential for you, you could try that, then bump up through the releases until you find one you're happy with.

Oh and I don't know if this is what's in your config files, but your code in your comment is using prettty quotes, like `“` , they should be standard double quotes like `"`.

**Comment by Unim8trix** [comment]
Verry strange: just typed in the exact same line of codes again in my editor..now it works. Magic :)

ok..no magic, I think its cause of the pretty quotes.  Many thanks (again) for the hint !

**Comment by earthlingdavey** [comment]
No problem
